### ISSUE TITLE
There is no * for uncommited changes

### ISSUE THREAD

**Issue by mshahat** [mdo/config#10]
Hello, 

I'm a fan of your tools here. I've been using it for sometime. Some other git prompts , adds an * for uncommited changes. 

Can you add the same ?  

I'm showing an example where there was changes but there was no * here. I'm also attaching an example where you can see an * for uncommited changes. I will attached this prompt too. 

<img width="1137" alt="screen shot 2016-12-09 at 4 20 15 pm" src="https://cloud.githubusercontent.com/assets/8035442/21049089/39ec576e-be2c-11e6-9fa2-f04ceaf0b94c.png">

<img width="1114" alt="screen shot 2016-12-09 at 4 26 26 pm" src="https://cloud.githubusercontent.com/assets/8035442/21049095/45df92a2-be2c-11e6-87e7-185866d8829b.png">
[git-prompt.txt](https://github.com/mdo/config/files/642125/git-prompt.txt)
[bash_profile_course.txt](https://github.com/mdo/config/files/642126/bash_profile_course.txt)

Thanks,

**Comment by mdo** [comment]
Hey there! That'd be an interesting idea, but I don't think I'll be adding it to my own config :). Definitely feel free to fork this repo though and add it yourself so you can share with others <3.
